"""
add_engagement_names.py

Creates an "Engagement Name" text column on the Nexus Engagements board
and populates it from engagements.csv.

Usage:
    py add_engagement_names.py <MONDAY_API_KEY>
"""

# standard library stuff - csv and json for reading our files,
# os to build file paths that work on any machine, sys to grab
# the api key from the command line, time so can add delays between requests
import csv
import json
import os
import sys
import time

# requests is the go-to library for making http calls in python
import requests

# keeping all the config at the top so it's easy to swap out if board IDs change
MONDAY_API_URL    = "https://api.monday.com/v2"
ENGAGEMENTS_BOARD_ID = "18409314022"

# building the desktop path dynamically so this works on any user's machine
DESKTOP           = os.path.join(os.path.expanduser("~"), "Desktop")
ENGAGEMENTS_CSV   = os.path.join(DESKTOP, "engagements.csv")

# this lookup file was generated by load_to_monday.py - it maps our engagement IDs
# to the internal monday item IDs - need to update the right rows
LOOKUP_JSON       = os.path.join(DESKTOP, "engagement_lookup.json")

# monday's API has rate limits so adding a small delay between requests to avoid getting blocked
REQUEST_DELAY     = 0.4


def monday_request(api_key, query, variables=None):
    # monday uses graphql over http, so every request goes to the same endpoint
    # with different query bodies rather than different URLs
    headers = {
        "Authorization": api_key,       # api key goes straight in the header
        "Content-Type": "application/json",
        "API-Version": "2024-10",       # pinning the API version so behavior doesn't change if monday updates
    }
    payload = {"query": query}
    if variables:
        # variables are optional - only attach them if you have some
        payload["variables"] = variables
    resp = requests.post(MONDAY_API_URL, json=payload, headers=headers)
    resp.raise_for_status()  # throws an error immediately if you get a 4xx or 5xx back
    data = resp.json()
    if "errors" in data:
        # graphql can return a 200 status but still have errors in the body, so check for that too
        raise RuntimeError(f"Monday API error: {data['errors']}")
    return data


def get_or_create_column(api_key):
    """Return the column ID for 'Engagement Name', creating it if it doesn't exist."""
    # first, pull all existing columns from the board so it can check if
    # the column already exists - no point creating a duplicate
    query = """
    query ($board_id: ID!) {
        boards(ids: [$board_id]) {
            columns { id title type }
        }
    }
    """
    data = monday_request(api_key, query, {"board_id": ENGAGEMENTS_BOARD_ID})

    # loop through and see if already have an "Engagement Name" text column
    for col in data["data"]["boards"][0]["columns"]:
        if col["title"] == "Engagement Name" and col["type"] == "text":
            # column already exists, just return its ID and move on
            print(f"Column already exists: {col['id']}")
            return col["id"]

    # column doesn't exist yet so create it here
    # ColumnType is an enum in monday's API - "text" is the plain text column type
    mutation = """
    mutation ($board_id: ID!, $title: String!, $column_type: ColumnType!) {
        create_column(
            board_id: $board_id
            title: $title
            column_type: $column_type
        ) { id }
    }
    """
    data = monday_request(api_key, mutation, {
        "board_id":    ENGAGEMENTS_BOARD_ID,
        "title":       "Engagement Name",
        "column_type": "text",
    })
    # grab the new column ID from the response so can use it in the next step
    col_id = data["data"]["create_column"]["id"]
    print(f"Created column: {col_id}")
    return col_id


def upload_names(api_key, col_id):
    # read the csv into a dictionary so we can look up names by engagement ID quickly
    with open(ENGAGEMENTS_CSV, newline="", encoding="utf-8") as f:
        eng_names = {row["engagement_id"]: row["engagement_name"]
                     for row in csv.DictReader(f)}

    # load the lookup file this gives us the monday item ID for each engagement

    with open(LOOKUP_JSON, encoding="utf-8") as f:
        lookup = json.load(f)   # {engagement_id: monday_item_id}

    # change_column_value is monday's mutation for updating a single cell
    # pass board_id, item_id, the column thats being targeted, and the new value
    mutation = """
    mutation ($board_id: ID!, $item_id: ID!, $col_id: String!, $value: JSON!) {
        change_column_value(
            board_id: $board_id
            item_id:  $item_id
            column_id: $col_id
            value:    $value
        ) { id }
    }
    """

    for eng_id, name in eng_names.items():
        # look up the monday item ID for this engagement
        monday_id = lookup.get(eng_id)
        if not monday_id:
            # if it's not in the lookup something went wrong during the original load
            print(f"  [SKIP] {eng_id}: not in lookup")
            continue
        print(f"  {eng_id}: {name}")
        monday_request(api_key, mutation, {
            "board_id": ENGAGEMENTS_BOARD_ID,
            "item_id":  str(monday_id),         # monday expects item IDs as strings
            "col_id":   col_id,
            "value":    json.dumps(name),        # text column values need to be JSON encoded
        })
        # small pause between each request to stay within monday's rate limits
        time.sleep(REQUEST_DELAY)


def main(api_key):
    # step 1, make sure the column exists and get its ID
    print("Checking / creating Engagement Name column...")
    col_id = get_or_create_column(api_key)

    # step 2, fill in the engagement names for all 6 engagements
    print(f"\nUploading names (column id: {col_id})...")
    upload_names(api_key, col_id)

    print("\nDone.")


if __name__ == "__main__":
    # make sure the user passed an API key before doing anything
    if len(sys.argv) < 2:
        print("Usage: py add_engagement_names.py <MONDAY_API_KEY>")
        sys.exit(1)
    main(sys.argv[1])
